(define (square x) (* x x))
(define (fast-expt b n)
    (define (iter a b n)
        (cond   ((<= n 1) a)
                ((even? n)
                    (iter (* a (square b)) b (/ n 2)))
                ((iter (* a b) b (- n 1)))
               ))
    (iter 1 b n))